---
title: "wnum"
author: "Eva Zadorozny"
date: "2023-03-31"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
# Needed libraries
library(tuneR) 
library(seewave) # for spectro
library(reshape2)
library(dplyr)
library(purrr)

```

```{r}

thumb <- function(ANGEL, COCO, ID){
# angel - bird or man?
# coco - filename
# id - id number
  
wav <- readWave(paste0("Voices/", COCO, ".wav")) #HERE

#wav

# duration of the .wav file in time of seconds
dur <- duration(wav)

#dur

# spectrograph
# gives three measurements: Time, Frequency, Amplitude
ss = spectro(wav)

# Pull all three measurements from spectro graph
# melt() converts wide format into long format
  
# For amplitude, replace Var1 and Var 2 with new variables
amp = melt(ss$amp, value.name = "Amplitude") %>% 
  select(FrequencyIndex = Var1, TimeIndex = Var2, Amplitude)
  
#amp

# For frequency, add matching row num and change value of frequency
# Frequency value from kHz to Hz
frequent = melt(ss$freq, value.name = "Frequency") %>% 
  mutate(FrequencyIndex = row_number(), Frequency = Frequency * 1000)
  
# For time, add a TimeIndex for left join later on
tm = melt(ss$time, value.name = "Time") %>% 
  mutate(TimeIndex = row_number())
  
# left join all datasets together 
# Only need Time, Frequency, and Amplitude
  numeric_data <- amp %>% 
    left_join(frequent, by = "FrequencyIndex") %>% 
    left_join(tm, by = "TimeIndex") %>% 
    select(FrequencyIndex,Time, Frequency, Amplitude) %>% 
    filter(Time >= 1) %>% # shed first second of data
    filter(Time <= (dur - 1)) # shed last second of data
  
#View(numeric_data, title="Numeric Data")
# 30,976 rows
  
# Get the sample of data by dividing the number of rows by 
# 10 We don't need tons of columns, just 10
segment <- trunc(nrow(numeric_data) / 10) #SLICE = 10
# print(segment)
# 3,097 rows

# Randomly sample from 10 equi sections  
rows <- rows <- sapply(1:segment, FUN = function(multiple) {
    numeric_data[round(sample(((multiple - 1) * segment + 1):(segment*multiple), size=1)),]
  })

# We only want the amplitude, which is in row 4 of all columns
row <- data.frame(rows[4,])

# Give this row meaningful column names so they will match
# the dataframe we will bind this row to in FileParser.R
colnames(row) <- colnames(row, do.NULL = FALSE, prefix = "Amp")

# Take slices of equal length  
# SLICE = 10
dataToReturn <- sapply(1:10, FUN = function(multiple) {
    numeric_data[((multiple - 1) * segment + 1):(segment*multiple),]
  })

colnames_generator <- function(prefix, range) {
  sapply(range, function(index) {
    paste(prefix, index, sep="") # concat the two values together with nothing separating
  })
}

# Only take amplitude, row 4
dataToReturn <- data.frame(dataToReturn[4,])

# concatenates the two values together with nothing separating
colnames_generator <- function(prefix, range) {
  sapply(range, function(index) {
    paste(prefix, index, sep="") 
  })
}

column_names <- colnames_generator("Amp", 1:ncol(dataToReturn))
colnames(dataToReturn) <- column_names

#View(dataToReturn, title = "Wave Return")

# keep first five rows
# call it actor, id = 1
# save as actor1.data

row5  <- dataToReturn[1:5, ]
#View(row5)

# Add multiple columns to dataframe
birdorman = ANGEL
id = c(ID) #HERE
thmb <- cbind(row5, birdorman, id) #HERE

View(thmb) #HERE
save(thmb,COCO, file=paste("Voices/", COCO,".Rda")) #HERE, HERE
}

#man thumbprints;
thumb(ANGEL = "man", COCO = "actor1", ID = 1)
thumb(ANGEL = "man", COCO = "actor2", ID = 2)
thumb(ANGEL = "man", COCO = "actor3", ID = 3)
thumb(ANGEL = "man", COCO = "actor4", ID = 4)
thumb(ANGEL = "man", COCO = "actor5", ID = 5)
thumb(ANGEL = "man", COCO = "actor6", ID = 6)
thumb(ANGEL = "man", COCO = "actor7", ID = 7)
thumb(ANGEL = "man", COCO = "actor8", ID = 8)
thumb(ANGEL = "man", COCO = "actor9", ID = 9)
thumb(ANGEL = "man", COCO = "actor10", ID = 10)

#bird thumbprints;
thumb(ANGEL = "bird", COCO = "bird1", ID = 1)
thumb(ANGEL = "bird", COCO = "bird2", ID = 2)
thumb(ANGEL = "bird", COCO = "bird3", ID = 3)
thumb(ANGEL = "bird", COCO = "bird4", ID = 4)
thumb(ANGEL = "bird", COCO = "bird5", ID = 5)
thumb(ANGEL = "bird", COCO = "bird6", ID = 6)
thumb(ANGEL = "bird", COCO = "bird7", ID = 7)
thumb(ANGEL = "bird", COCO = "bird8", ID = 8)
thumb(ANGEL = "bird", COCO = "bird9", ID = 9)
thumb(ANGEL = "bird", COCO = "bird10", ID = 10)

#bind into analysis data model (ADaM)
r1 <- load("Voices/ actor1 .Rda")
r2 <- load("Voices/ actor2 .Rda")
load("Voices/ actor3 .Rda")
r4 <- load("Voices/ actor4 .Rda")
r5 <- load("Voices/ actor5 .Rda")
r6 <- load("Voices/ actor6 .Rda")
r7 <- load("Voices/ actor7 .Rda")
r8 <- load("Voices/ actor8 .Rda")
r9 <- load("Voices/ actor9 .Rda")
r10 <- load("Voices/ actor10 .Rda")

f1 <- load("Voices/ bird1 .Rda")
f2 <- load("Voices/ bird2 .Rda")
f3 <- load("Voices/ bird3 .Rda")
f4 <- load("Voices/ bird4 .Rda")
f5 <- load("Voices/ bird5 .Rda")
f6 <- load("Voices/ bird6 .Rda")
f7 <- load("Voices/ bird7 .Rda")
f8 <- load("Voices/ bird8 .Rda")
f9 <- load("Voices/ bird9 .Rda")
f10 <- load("Voices/ bird10 .Rda")

ADaM <- rbind(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10,
              f1, f2, f3, f4, f5, f6, f7, f8, f9, f10)
save(ADaM, file="ADaM.rda")
```
```{r}

thumb <- function(ANGEL, COCO, ID){
# angel - bird or man?
# dset - dataset name (same as filename)
# coco - filename
# id - id number
  
wav <- readWave(paste0("Voices/", COCO, ".wav")) #HERE

#wav

# duration of the .wav file in time of seconds
dur <- duration(wav)

#dur

# spectrograph
# gives three measurements: Time, Frequency, Amplitude
ss = spectro(wav)

# Pull all three measurements from spectro graph
# melt() converts wide format into long format
  
# For amplitude, replace Var1 and Var 2 with new variables
amp = melt(ss$amp, value.name = "Amplitude") %>% 
  select(FrequencyIndex = Var1, TimeIndex = Var2, Amplitude)
  
#amp

# For frequency, add matching row num and change value of frequency
# Frequency value from kHz to Hz
frequent = melt(ss$freq, value.name = "Frequency") %>% 
  mutate(FrequencyIndex = row_number(), Frequency = Frequency * 1000)
  
# For time, add a TimeIndex for left join later on
tm = melt(ss$time, value.name = "Time") %>% 
  mutate(TimeIndex = row_number())
  
# left join all datasets together 
# Only need Time, Frequency, and Amplitude
  numeric_data <- amp %>% 
    left_join(frequent, by = "FrequencyIndex") %>% 
    left_join(tm, by = "TimeIndex") %>% 
    select(FrequencyIndex,Time, Frequency, Amplitude) %>% 
    filter(Time >= 1) %>% # shed first second of data
    filter(Time <= (dur - 1)) # shed last second of data
  
#View(numeric_data, title="Numeric Data")
# 30,976 rows
  
# Get the sample of data by dividing the number of rows by 
# 10 We don't need tons of columns, just 10
segment <- trunc(nrow(numeric_data) / 10) #SLICE = 10
# print(segment)
# 3,097 rows

# Randomly sample from 10 equi sections  
rows <- rows <- sapply(1:segment, FUN = function(multiple) {
    numeric_data[round(sample(((multiple - 1) * segment + 1):(segment*multiple), size=1)),]
  })

# We only want the amplitude, which is in row 4 of all columns
row <- data.frame(rows[4,])

# Give this row meaningful column names so they will match
# the dataframe we will bind this row to in FileParser.R
colnames(row) <- colnames(row, do.NULL = FALSE, prefix = "Amp")

# Take slices of equal length  
# SLICE = 10
dataToReturn <- sapply(1:10, FUN = function(multiple) {
    numeric_data[((multiple - 1) * segment + 1):(segment*multiple),]
  })

colnames_generator <- function(prefix, range) {
  sapply(range, function(index) {
    paste(prefix, index, sep="") # concat the two values together with nothing separating
  })
}

# Only take amplitude, row 4
dataToReturn <- data.frame(dataToReturn[4,])

# concatenates the two values together with nothing separating
colnames_generator <- function(prefix, range) {
  sapply(range, function(index) {
    paste(prefix, index, sep="") 
  })
}

column_names <- colnames_generator("Amp", 1:ncol(dataToReturn))
colnames(dataToReturn) <- column_names

#View(dataToReturn, title = "Wave Return")

# keep first five rows
# call it actor, id = 1
# save as actor1.data

row5  <- dataToReturn[1:5, ]
#View(row5)

# Add multiple columns to dataframe
birdorman = ANGEL
id = c(ID) #HERE
thumbprint <- cbind(row5, birdorman, id) 
save(thumbprint, file="thumbprint.Rda") 
}

# thumbprint gets over-written
# it is all for ADaM

#man thumbprints;
thumb(ANGEL = "man", COCO = "actor1", ID = 1) #HERE, HERE
load("thumbprint.Rda")
r1 <- thumbprint #HERE


thumb(ANGEL = "man", COCO = "actor2", ID = 2)#HERE, HERE
load("thumbprint.Rda")
r2 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor3", ID = 3)#HERE, HERE
load("thumbprint.Rda")
r3 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor4", ID = 4)#HERE, HERE
load("thumbprint.Rda")
r4 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor5", ID = 5)#HERE, HERE
load("thumbprint.Rda")
r5 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor6", ID = 6)#HERE, HERE
load("thumbprint.Rda")
r6 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor7", ID = 7)#HERE, HERE
load("thumbprint.Rda")
r7 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor8", ID = 8)#HERE, HERE
load("thumbprint.Rda")
r8 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor9", ID = 9)#HERE, HERE
load("thumbprint.Rda")
r9 <- thumbprint #HERE

thumb(ANGEL = "man", COCO = "actor10", ID = 10)#HERE, HERE
load("thumbprint.Rda")
r10 <- thumbprint #HERE

#bird thumbprints
thumb(ANGEL = "bird", COCO = "bird1", ID = 1) #HERE, HERE
load("thumbprint.Rda")
f1 <- thumbprint #HERE


thumb(ANGEL = "bird", COCO = "bird2", ID = 2)#HERE, HERE
load("thumbprint.Rda")
f2 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird3", ID = 3)#HERE, HERE
load("thumbprint.Rda")
f3 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird4", ID = 4)#HERE, HERE
load("thumbprint.Rda")
f4 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird5", ID = 5)#HERE, HERE
load("thumbprint.Rda")
f5 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird6", ID = 6)#HERE, HERE
load("thumbprint.Rda")
f6 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird7", ID = 7)#HERE, HERE
load("thumbprint.Rda")
f7 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird8", ID = 8)#HERE, HERE
load("thumbprint.Rda")
f8 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird9", ID = 9)#HERE, HERE
load("thumbprint.Rda")
f9 <- thumbprint #HERE

thumb(ANGEL = "bird", COCO = "bird10", ID = 10)#HERE, HERE
load("thumbprint.Rda")
f10 <- thumbprint #HERE

#bind into analysis data model (ADaM)
ADaM <- rbind(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10,
              f1, f2, f3, f4, f5, f6, f7, f8, f9, f10)
save(ADaM, file="ADaM.rda")

View(ADaM)
```


